# Generated by Django 5.2 on 2025-05-06 12:24

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='default_logo.png', upload_to=app1.models.profile_photo_upload_path),
        ),
    ]
